name: 'Create Black Duck Policy Action'
description: 'Create a policy within Black Duck'
author: 'Synopsys, Inc.'
inputs:
  blackduck-url:
    description: 'Url of Black Duck instance'
    required: true
  blackduck-api-token:
    description: 'API Token for Black Duck instance'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
