name: 'Create Black Duck Policy Action'
description: 'Create a policy within Black Duck'
author: 'Synopsys, Inc.'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
